[project]
name = "mlprojects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=4.4.1",
    "dash-bootstrap-components>=2.0.4",
    "kagglehub>=1.0.2",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "onnxmltools>=1.16.0",
    "optuna>=4.9.0",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "scikit-learn>=1.9.0",
    "skl2onnx>=1.20.0",
    "tensorflow>=2.21.0",
]
